# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dtw.grpc.invoke.invoke_pb2 as invoke__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in invoke_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InvokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartActor = channel.unary_unary(
                '/Invoker/StartActor',
                request_serializer=invoke__pb2.StartActorRequest.SerializeToString,
                response_deserializer=invoke__pb2.StartActorResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/Invoker/Invoke',
                request_serializer=invoke__pb2.InvokeRequest.SerializeToString,
                response_deserializer=invoke__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/Invoker/GetResult',
                request_serializer=invoke__pb2.ResultRequest.SerializeToString,
                response_deserializer=invoke__pb2.ResultResponse.FromString,
                _registered_method=True)
        self.GetData = channel.unary_unary(
                '/Invoker/GetData',
                request_serializer=invoke__pb2.GetDataRequest.SerializeToString,
                response_deserializer=invoke__pb2.GetDataResponse.FromString,
                _registered_method=True)


class InvokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartActor': grpc.unary_unary_rpc_method_handler(
                    servicer.StartActor,
                    request_deserializer=invoke__pb2.StartActorRequest.FromString,
                    response_serializer=invoke__pb2.StartActorResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=invoke__pb2.InvokeRequest.FromString,
                    response_serializer=invoke__pb2.InvokeResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=invoke__pb2.ResultRequest.FromString,
                    response_serializer=invoke__pb2.ResultResponse.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=invoke__pb2.GetDataRequest.FromString,
                    response_serializer=invoke__pb2.GetDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Invoker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Invoker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Invoker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Invoker/StartActor',
            invoke__pb2.StartActorRequest.SerializeToString,
            invoke__pb2.StartActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Invoker/Invoke',
            invoke__pb2.InvokeRequest.SerializeToString,
            invoke__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Invoker/GetResult',
            invoke__pb2.ResultRequest.SerializeToString,
            invoke__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Invoker/GetData',
            invoke__pb2.GetDataRequest.SerializeToString,
            invoke__pb2.GetDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
